HH домашняя Todo List
bannovdaniil/hh_todolist pull request #1
Opened 2023-02-10 13:43 UTC by bannovdaniil

все подробности в Readme.md

2023-02-13 18:03 UTC, a-nikishin requested changes

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/config/Constants.java
> +  public static final DateTimeFormatter DATE_TIME_SPACE = DateTimeFormatter.ofPattern(DATE_TIME_STRING);
Для чего тебе это нужно? Formatter вообще не используется, паттерн-строка только на получении конкретной таски, а при получении списка в твоём случае это не работает. Можешь проверить, сравнив ответы на запросы конкретной таски и всего списка.

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/dao/GenericDao.java
> +public class GenericDao<T> {
Для чего тебе тут нужно <T>?
А если нужно, то почему у тебя в сервисе `GenericDao genericDao;`, а не `GenericDao<Task> genericDao;`

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/dao/GenericDao.java
> +  public <T> T get(Class<T> clazz, Long taskId) {
Если у тебя GenericDao, то он должен быть универсален, а не конкретно для тасок. А если тебе нужен dao для тасок, то он должен называться немного не так

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/dao/GenericDao.java
> +  }
То же самое, что и выше

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/dao/GenericDao.java
> +  }
Опять про универсальность. Это должно быть в дао про таски, а не в общем. Либо если хочешь всё в общем, то можно убрать сортировку или через критерии.
К getAll(TaskStatus taskStatus) это также относится, но в том случае фильтровать можно через критерии

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/dao/GenericDao.java
> +  }
Это всё и к getAll() относится
В метод createQuery() можно и нужно вторым параметром передавать класс, который ты ожидаешь. Например, `sessionFactory.getCurrentSession().createQuery("FROM Task", Task.class)` (кстати, в hql `SELECT t` не обязательно писать). Это может помочь избежать неожиданных ошибок.
Судя по описанию метода на выходе ты ожидаешь `List<TaskDao>`, а как ты этого добиваешься ?

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/entity/TaskStatus.java
> +  }
Не нужно всё это делать. У енамов есть встроенный метод преобразования строк в енам.

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/mapper/TaskMapper.java
> +  }
В каком случае тебе это может пригодиться? Обычно ты либо создаёшь новый и у тебя есть только текст, либо ты достаёшь из базы по id-шке

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/mapper/TaskMapper.java
> +  }
Это есть куда прикрутить, но у тебя это нигде не используется. А ещё это можно оставить и здесь, а можно и в сервисе, как и taskToDto (просто на заметку).
Но что интереснее, лучше делать данные неизменяемыми (когда это возможно). А в данном случае это делается легко (например, через Stream). Можешь переписать на него?

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/resource/TodoListResource.java
> +  public List<TaskDto> getAllTask(@QueryParam(value = "status") String status) {
Тут лучше сразу принимать енам.

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/service/TodoListService.java
> +package ru.hh.todolist.service;
Смысла в этом интерфейсе нет. Это не ошибка, но без него было бы проще.

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    if (taskName == null || taskName.isBlank()) {
В этих целях лучше использовать StringUtils:
```suggestion
    if (StringUtils.isBlank(taskName)) {
```

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    checkId(taskId);
Аналогично (проверки в ресурсах)

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/resource/TodoListResource.java
> +                            @FormParam(value = "status") String status) {
И тут тоже

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    }
А такие проверки делаются в ресурсах

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    return genericDao.getAll(taskStatus);
А можешь это через Optional написать (это не обязательно)?

2023-02-13 18:03 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    if (taskName != null && !taskName.isBlank()) {
```suggestion
    if (StringUtils.isBlank(taskName)) {
```

2023-02-13 20:44 UTC, bannovdaniil commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    if (taskName == null || taskName.isBlank()) {
посмотрел исходник, особого преимущества не увидел, ради эксперимента сделал. Простой isBlank() проверяет 
`if (ch != ' ' && ch != '\t' && !CharacterDataLatin1.instance.isWhitespace(ch)) {
`
не понимаю, зачем это двойная проверка.
 в StringUtils только 
  `if ((Character.isWhitespace(str.charAt(i)) == false)) {
  `

2023-02-13 21:09 UTC, bannovdaniil commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    checkId(taskId);
сколько проектов столько и вариантов :) у кого в сервисе проверяют, у кого в ресурсах, запомнил в HH проверяем в ресурсах.
если в сервисе можно по логам,  понять в каком ендпоинте произошла ошибка, как это делать в ресурсах не совсем понятно.

2023-02-13 21:16 UTC, bannovdaniil commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    if (taskName != null && !taskName.isBlank()) {
только скорее всего тут с инверсией
`if (**!**StringUtils.isBlank(taskName)) {`

2023-02-13 21:23 UTC, bannovdaniil commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    return genericDao.getAll(taskStatus);
Да сделал, это хорошее предложение.

2023-02-13 21:38 UTC, bannovdaniil commented on src/main/java/ru/hh/todolist/mapper/TaskMapper.java
> +  }
написал по привычке, на ендпПоинт можно принимать DTO и ее потом мапить в объект, удалил за ненадобностью.

2023-02-14 19:33 UTC, bannovdaniil commented on src/main/java/ru/hh/todolist/config/Constants.java
> +  public static final DateTimeFormatter DATE_TIME_SPACE = DateTimeFormatter.ofPattern(DATE_TIME_STRING);
Formatter во время тестирования помогает т.к. откидывает нано, а формат даты влияет на формирование json

`@JsonFormat(pattern = Constants.DATE_TIME_STRING)`

вот так с ним и без: 

![image](https://user-images.githubusercontent.com/96119195/218838445-3137dfa8-ccc9-4eaf-b440-61e53aedd9fc.png)
![image](https://user-images.githubusercontent.com/96119195/218838544-5a95a8c9-9e00-4edd-bfc7-65afcbf83756.png)

2023-02-14 21:30 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/config/Constants.java
> +  public static final DateTimeFormatter DATE_TIME_SPACE = DateTimeFormatter.ofPattern(DATE_TIME_STRING);
Вопрос был связан с тем, что на getAll() у тебя это не работало, т.к. отдавался список entity, а не dto. Теперь вопрос отпал.

2023-02-14 21:33 UTC, a-nikishin commented on src/main/java/ru/hh/todolist/service/impl/TodoListServiceImpl.java
> +    if (taskName != null && !taskName.isBlank()) {
В данном случае инверсию правильно сделать через `if (StringUtils.isNotBlank(taskName))`

2023-02-16 07:22 UTC, a-nikishin approved these changes

2023-02-16 17:45 UTC, merged